name: resume-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install PNPM
              run: |
                  sudo apt install npm
                  npm i --location=global pnpm@7

            - name: Install Depedencies
              run: make install
